# 本编排包含4个博客相关服务，共享一个网络，前后台连接同一个数据库

# blog: 博客前台，每次开发完重新build
# admin: 博客后台，每次开发完重新build
# db: 博客数据库，基于官方mysql5.7二次开发，初次创建卷时，会自动调用sql文件生成一些初始数据。。，除非更改初始化数据，否则不需要再重新build
# db-view ：数据库可视化工具，直接使用官方phpmyadmin

x-common-environment: &common-environment # 环境变量
  TZ: Asia/Shanghai             # 所有服务的时区
  MYSQL_ROOT_PASSWORD: 991015   # mysql-数据库密码
  MYSQL_DATABASE: blog          # mysql-自动创建的表
  PMA_HOST: elin-blog-db        # phpmyadmin-连接的数据库地址
  PMA_PORT: 3306                # phpmyadmin-连接的数据库端口
  DB_HOST: elin-blog-db         # 前后台连接的-数据库地址
  DB_PORT: 3306                 # 前后台连接的-数据库端口
  DB_USER: root                 # 前后台连接的-数据库用户
  DB_PASSWORD: 991015           # 前后台连接的-数据库密码
  DB_NAME: blog                 # 前后台连接的-数据库表
  ADMIN_USERNAME: admin         # 管理后台-登录用户名
  ADMIN_PASSWORD: admin123456   # 管理后台-登录密码
  
services:
  blog:
    build:
      context: . # 当前目录
      dockerfile: Dockerfile
      args:
        TARGET: blog # 传递 TARGET 参数为 blog
    image: crpi-a7p27yxlrmekg1a3.cn-beijing.personal.cr.aliyuncs.com/elin/elin-blog:latest
    container_name: elin-blog
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      <<: *common-environment

  admin:
    build:
      context: . # 当前目录
      dockerfile: Dockerfile
      args:
        TARGET: admin # 传递 TARGET 参数为 admin
    image: crpi-a7p27yxlrmekg1a3.cn-beijing.personal.cr.aliyuncs.com/elin/elin-blog-admin:latest
    container_name: elin-blog-admin
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      <<: *common-environment
      
  db:
    build:
      context: ./projects/db 
      dockerfile: Dockerfile
    image: crpi-a7p27yxlrmekg1a3.cn-beijing.personal.cr.aliyuncs.com/elin/elin-blog-db:latest
    container_name: elin-blog-db
    environment:
      <<: *common-environment
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
      
  db-view:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      <<: *common-environment
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
