# 使用官方 Node.js Alpine 镜像作为基础镜像
FROM node:18-alpine AS build

# 设置工作目录
WORKDIR /app

# 安装 pnpm
RUN npm install -g pnpm

# 复制 package.json 和 pnpm-lock.yaml，仅复制依赖文件来缓存依赖安装步骤
COPY package.json pnpm-lock.yaml  pnpm-workspace.yaml ./

COPY packages ./packages

# 安装依赖
RUN pnpm install

# 复制其余项目文件
COPY . .

# 在构建时启用 standalone 模式，输出一个最小化的产物
ENV NEXT_OUTPUT=standalone

# 构建 Next.js 项目
RUN pnpm build:admin

# 复制产物
RUN mkdir -p projects/admin/dist/build/standalone/dist/build/static && \
    cp -r projects/admin/dist/build/static projects/admin/dist/build/standalone/projects/admin/dist/build/static

RUN cp -r projects/admin/public projects/admin/dist/build/standalone/projects/admin/public


# 第二阶段：最终镜像
FROM node:18-alpine AS production

# 设置工作目录
WORKDIR /app

COPY --from=build /app/projects/admin/dist/build/standalone /app

EXPOSE 3001

ENV PORT=3001

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
ENV HOSTNAME="0.0.0.0"

# 启动 Next.js 项目
CMD ["node", "projects/admin/server.js"]
